- name: play1
  hosts: web
  tasks:
    - name: PLAY-1 AND T-1
      ansible.builtin.debug:
        msg: "hello iam from play1 nad task1"


- name: PLAY-2
  hosts: web
  tasks:
    - name: PL6Y-2 AND -2
      ansible.builtin.debug:
        msg: "hello iam from play1 nad task1"