- name: ansible
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the value
             ansible.builtin.debug:
              msg: "hello iam learning {{course}} from sivakumar and the duration is {{duration}}, and the title is {{title}}"
