- name: ansible
  hosts: web
  vars_prompt:
  - name: USERNAME
    prompt: please enter your username
    private: false

  - name: PASSWORD
    prompt: please enter password
    private: true

  tasks:
    - name: print the information
      ansible.builtin.debug:
          msg: "hi iam learning {{course}} from {{trainer}} and the duration is {{duration}}"