- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "hi {{course | default('ansible')}} "

- name: upper case
  hosts: localhost
  vars:
    message: "sameera i love u"
  tasks:
    - name: upper case
      ansible.builtin.debug:
       msg: "hlo {{message | upper }}"


- name: lower case
  hosts: localhost
  vars:
    name: "imran i love you 2"
  tasks:
  - name: lower case
    ansible.builtin.debug:
      msg: "hi {{name | lower }}"



- name: removwe duplicate
  hosts: localhost
  vars:
    number: [1, 2, 3, 4, 5, 6, 6, 5]

  tasks:
  - name: remove duplicate
    ansible.builtin.debug:
      msg: "{{number | unique}}"


- name: print min and max age
  hosts: localhost
  vars:
    age : [25, 30, 15, 18, 89]

  tasks:
    - name: printing min and max age
      ansible.builtin.debug:
        msg: "hi min age is {{age | min}}, and max age is {{age | max}}"


- name: dictionary converts
  hosts: localhost
  vars:
    my_dict:
     course: ansible
     trainer: sameera
     duration: 120hrs
  tasks:
    - name: before convert
      ansible.builtin.debug:
        msg: "before convert: {{my_dict}}"
    - name: after convert
      ansible.builtin.debug:
        msg: "after convert: {{my_dict | dict2items}}"


- name: convert items to dictionary
  hosts: localhost
  vars:
    my_list:
    - {'key': 'course', 'value': 'ansible'}
    - {'key': 'trainer', 'value': 'sameera'}
    - {'key': 'duration', 'value': '120hrs'}
  tasks:
   - name: before convert
     ansible.builtin.debug:
       msg: "before convert: {{my_list}}"

   - name: after convert
     ansible.builtin.debug:
        msg: "after convert: {{my_list | items2dict}}"