- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "hi {{course | default('ansible')}} "

- name: upper case
  hosts: localhost
  vars:
    name: "sameera i love u"
  tasks:
  - name: upper case
    ansible.builtin.debug:
      msg: "hlo {{name | upper }}"


- name: lower case
  hosts: localhost
  vars:
    name: "imran i love you 2"
  tasks:
  - name: lower case
    ansible.builtin.debug:
      msg: "hi {{name | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 3, 4, 5, 5, 6]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "number{{numbers | "unique"}}"