- name: install packages
  hosts: web
  become: yes
  tasks:
    - name: install the packages
      ansible.builtin.dnf:
        name: "{{ item.name }}"
        state: "{{ item.state }}"

      loop:

      - { name: 'mysql', state: 'latest' }
      - { name: 'nginx', state: 'present' }
      - { name: 'postfix', state: 'absent' }